[theme]
primaryColor = "#58A6FF"
backgroundColor = "#0F1419"
secondaryBackgroundColor = "#1A2027"
textColor = "#F0F2F4"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
